server:
  port: 8763
spring:
  application:
    name: consumer-demo
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  main:
    allow-bean-definition-overriding: true # 有相同名字的Feign注册不会重复注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心项目的地址和端口
app:
  service-url: http://PROVIDER-SERVICE/



